# output directory, generated dynamically on each run
run:
  dir: /gws/ssde/j25b/iecdt/amorgan/benchmark_data_CB/model_outputs/logs/${name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: /gws/ssde/j25b/iecdt/amorgan/benchmark_data_CB/model_outputs/logs/${name}/multiruns/
  subdir: ${now:%Y-%m-%d}_${now:%H-%M-%S}/${hydra.job.num}
job:
  chdir: True